version: '3.5'


services:
  postgres:
    container_name: epetitions_database
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5435:5432"

volumes:
  postgres-db:
    driver: local